# Generated by Django 3.0.8 on 2020-07-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200705_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
