# Generated by Django 2.0.13 on 2020-07-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('system', '0002_auto_20200705_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('account_number', models.IntegerField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='MyWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_account_number', models.IntegerField(default=0)),
                ('my_balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
