# Generated by Django 3.0.7 on 2020-07-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200708_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywallet',
            name='my_bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.BankAccount'),
        ),
    ]
