# Generated by Django 3.0.8 on 2020-07-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
