# Generated by Django 3.0.7 on 2020-07-08 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_notification'),
        ('system', '0006_mywallet_my_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywallet',
            name='my_bank',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Customer'),
        ),
    ]
