# Generated by Django 3.0.8 on 2020-07-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20200709_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='step',
            new_name='status',
        ),
    ]
