# Generated by Django 3.0.7 on 2020-07-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
