# Generated by Django 3.0.7 on 2020-07-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_customer_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='background',
        ),
    ]
