# Generated by Django 3.0.7 on 2020-06-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(default='root', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chef',
            name='username',
            field=models.CharField(default='root', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='root', max_length=30, unique=True),
        ),
    ]
